start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
accordion-padding = 60

after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.bottom =     10
outer.top = [{ monitor."AORUS FO48U" = 500 }, 10]
outer.left = [{ monitor."AORUS FO48U" = 400 }, 10]
outer.right = [{ monitor."AORUS FO48U" = 400 }, 10]

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

# - Modifiers.      cmd, alt, ctrl, shift
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
[mode.main.binding]
cmd-h = [] # disable hide

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-shift-l = 'focus left'
ctrl-alt-shift-j = 'focus down'
ctrl-alt-shift-k = 'focus up'
ctrl-alt-shift-semicolon = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# comms workspace
ctrl-alt-shift-1 = 'workspace comms'
ctrl-alt-shift-a = 'workspace comms'
cmd-ctrl-alt-shift-1 = 'move-node-to-workspace comms'
# browser workspace
ctrl-alt-shift-2 = 'workspace browser'
ctrl-alt-shift-s = 'workspace browser'
cmd-ctrl-alt-shift-2 = 'move-node-to-workspace browser'

# numbered workspaces and homerow aliesses
ctrl-alt-shift-3 = 'workspace 3'
ctrl-alt-shift-d = 'workspace 3'
cmd-ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'workspace 4'
ctrl-alt-shift-f = 'workspace 4'
cmd-ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'workspace 5'
ctrl-alt-shift-g = 'workspace 5'
cmd-ctrl-alt-shift-5 = 'move-node-to-workspace 5'

# plex workspace
ctrl-alt-shift-6 = 'workspace plex'
cmd-ctrl-alt-shift-6 = 'move-node-to-workspace plex'

# f1 workspaces
ctrl-alt-shift-r = ['workspace f1Main', 'workspace f1Secondary']
cmd-ctrl-alt-shift-r = ['move-node-to-workspace f1Secondary']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-backspace = 'mode service'

[workspace-to-monitor-force-assignment]
comms = 'DELL U2723QE'
f1Main = 'main'
f1Secondary = 'DELL U2723QE'

# browsers to browser workspace
[[on-window-detected]]
if.app-id = "company.thebrowser.Browser"
run = ['move-node-to-workspace browser']
[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = ['move-node-to-workspace browser']
[[on-window-detected]]
if.app-id = "com.apple.Safari"
run = ['move-node-to-workspace browser']
[[on-window-detected]]
if.app-id = "com.microsoft.edgemac"
run = ['move-node-to-workspace browser']

# comms
[[on-window-detected]]
if.app-id = "com.hnc.Discord"
run = ['move-node-to-workspace comms']
[[on-window-detected]]
if.app-id = "com.apple.MobileSMS"
run = ['move-node-to-workspace comms']
[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = ['move-node-to-workspace comms']

# plex
[[on-window-detected]]
if.app-id = "com.plex.Plex"
run = ['move-node-to-workspace plex']

# f1
[[on-window-detected]]
if.app-id = 'com.electron.multiviewer-for-f1'
if.window-title-regex-substring = "tracker"
run = 'move-node-to-workspace f1Secondary'
# [[on-window-detected]]
# if.app-id = 'com.electron.multiviewer-for-f1'
# if.window-title-regex-substring = "(Driver Tracker|Live Timing) — MultiViewer"
# run = ['layout floating', 'move-node-to-workspace f1Secondary']
# [[on-window-detected]]
# if.app-id = 'com.electron.multiviewer-for-f1'
# run = ['move-node-to-workspace f1Main']
# [[on-window-detected]]
# if.app-id = 'com.electron.multiviewer-for-f1'
# check-further-callbacks = true
# run = ['layout floating']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

# i dont know what these do yet
# alt-shift-h = ['join-with left', 'mode main']
# alt-shift-j = ['join-with down', 'mode main']
# alt-shift-k = ['join-with up', 'mode main']
# alt-shift-l = ['join-with right', 'mode main']
